KISSY.add(function(S){
	var data = {
		"list": [{
			"name_e": "G9",
			"name_c": "大7",
			"name": "基伍"
		}, {
			"name_e": "GO N1-Y",
			"name_c": "青云1",
			"name": "青橙"
		}, {
			"name_e": "neken NX",
			"name_c": "NX",
			"name": "尼凯恩"
		}, {
			"name_e": "A800",
			"name_c": "大智",
			"name": "基伍"
		}, {
			"name_e": "M1",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "M3",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "T10",
			"name_c": "",
			"name": "GUOMI"
		}, {
			"name_e": "X12",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "DOOV C1",
			"name_c": "小乔",
			"name": "朵唯"
		}, {
			"name_e": "C2",
			"name_c": "小黑",
			"name": "卓普"
		}, {
			"name_e": "X11",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "UUID1.0有CMNS的机型",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "V012",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "Bee2A",
			"name_c": "小蜜蜂",
			"name": "易丰"
		}, {
			"name_e": "T9986",
			"name_c": "",
			"name": "TELSDA"
		}, {
			"name_e": "M10",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "V015",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "Philips S301",
			"name_c": "",
			"name": "桑菲"
		}, {
			"name_e": "VOTO V5",
			"name_c": "紫云",
			"name": "VOTO"
		}, {
			"name_e": "M3+",
			"name_c": "",
			"name": "Lmi"
		}, {
			"name_e": "V003D",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "HIKe 868",
			"name_c": "",
			"name": "海客"
		}, {
			"name_e": "intki E83",
			"name_c": "小S",
			"name": "英特奇"
		}, {
			"name_e": "V008B",
			"name_c": "",
			"name": "HUALING"
		}, {
			"name_e": "M003",
			"name_c": "",
			"name": "DUXIU"
		}, {
			"name_e": "V012C",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "LM8",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "W1231",
			"name_c": "小C2",
			"name": "优思"
		}, {
			"name_e": "UBTEL U8",
			"name_c": "大U",
			"name": "UBTEL"
		}, {
			"name_e": "OKA5",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "S11",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "M010",
			"name_c": "",
			"name": "DUXIU"
		}, {
			"name_e": "X16",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "Bird XL100",
			"name_c": "枭龙",
			"name": "波导"
		}, {
			"name_e": "V015A",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "A902",
			"name_c": "",
			"name": "SAGA"
		}, {
			"name_e": "XG X800",
			"name_c": "X800",
			"name": "新迪恒"
		}, {
			"name_e": "S12",
			"name_c": "",
			"name": "Xianmi"
		}, {
			"name_e": "OKA3",
			"name_c": "小欧",
			"name": "欧奇"
		}, {
			"name_e": "HIKe 828A",
			"name_c": "X1",
			"name": "海客"
		}, {
			"name_e": "M7",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "X6",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "N18",
			"name_c": "",
			"name": "塞纳普"
		}, {
			"name_e": "C7",
			"name_c": "大黑",
			"name": "卓普"
		}, {
			"name_e": "9520",
			"name_c": "小黑二代",
			"name": "卓普"
		}, {
			"name_e": "V003E",
			"name_c": "",
			"name": "HUALING"
		}, {
			"name_e": "AUX W6",
			"name_c": "云精灵",
			"name": "奥克斯"
		}, {
			"name_e": "X18",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "VOTO V5",
			"name_c": "紫云",
			"name": "VOTO"
		}, {
			"name_e": "XC2S",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "V003",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "KS801",
			"name_c": "",
			"name": "kevoo"
		}, {
			"name_e": "M11",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "J333",
			"name_c": "",
			"name": "heeyu"
		}, {
			"name_e": "V008",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "S10",
			"name_c": "",
			"name": "Xianmi"
		}, {
			"name_e": "M15",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "S13",
			"name_c": "",
			"name": "Xianmi"
		}, {
			"name_e": "9515",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "P7",
			"name_c": "",
			"name": "佳业"
		}, {
			"name_e": "M13",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "UBTEL U9",
			"name_c": "超级U",
			"name": "UBTEL"
		}, {
			"name_e": "UNISTAR U5",
			"name_c": "",
			"name": "友信达"
		}, {
			"name_e": "UMI CROSS1",
			"name_c": "大红牛",
			"name": "优米"
		}, {
			"name_e": "V88",
			"name_c": "",
			"name": "锦润"
		}, {
			"name_e": "Kmi",
			"name_c": "",
			"name": "Kmi"
		}, {
			"name_e": "XG X800",
			"name_c": "X800",
			"name": "新迪恒"
		}, {
			"name_e": "H2",
			"name_c": "天涯",
			"name": "西维"
		}, {
			"name_e": "EF98A",
			"name_c": "柠檬",
			"name": "广信"
		}, {
			"name_e": "M6",
			"name_c": "",
			"name": "mikee"
		}, {
			"name_e": "cayon Q6",
			"name_c": "",
			"name": "英特奇"
		}, {
			"name_e": "JY-F1",
			"name_c": "",
			"name": "佳域"
		}, {
			"name_e": "Q3 mini",
			"name_c": "",
			"name": "cayon"
		}, {
			"name_e": "S200",
			"name_c": "",
			"name": "Xianmi"
		}, {
			"name_e": "V008",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "Newman",
			"name_c": "",
			"name": "纽曼"
		}, {
			"name_e": "V022",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "BLUEBO L300",
			"name_c": "蓝鲸",
			"name": "蓝天信"
		}, {
			"name_e": "KINGSUN S6",
			"name_c": "蓝莓",
			"name": "广信"
		}, {
			"name_e": "UTime_GX",
			"name_c": "",
			"name": "UTime"
		}, {
			"name_e": "IN310",
			"name_c": "",
			"name": "富士康"
		}, {
			"name_e": "guomi-K606",
			"name_c": "",
			"name": "GUOMI"
		}, {
			"name_e": "LORDOR",
			"name_c": "",
			"name": "lordor"
		}, {
			"name_e": "i6",
			"name_c": "",
			"name": "三魅"
		}, {
			"name_e": "X6088",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "C1",
			"name_c": "小白",
			"name": "卓普"
		}, {
			"name_e": "I9220",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "BROR G1",
			"name_c": "",
			"name": "果冻"
		}, {
			"name_e": "G1",
			"name_c": "",
			"name": "MGO"
		}, {
			"name_e": "X5",
			"name_c": "",
			"name": "Heexon"
		}, {
			"name_e": "YIMI_828",
			"name_c": "",
			"name": "金盛"
		}, {
			"name_e": "T6100",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "H7",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "NX",
			"name_c": "",
			"name": "青橙"
		}, {
			"name_e": "MOGU H6",
			"name_c": "",
			"name": "MOGU"
		}, {
			"name_e": "IMI",
			"name_c": "",
			"name": "顺隆"
		}, {
			"name_e": "P~7",
			"name_c": "",
			"name": "三魅"
		}, {
			"name_e": "Bird XL200",
			"name_c": "",
			"name": "波导"
		}, {
			"name_e": "AMOI N850",
			"name_c": "N850",
			"name": "夏新"
		}, {
			"name_e": "HUAWEI",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "Q22",
			"name_c": "",
			"name": "红星"
		}, {
			"name_e": "M128A",
			"name_c": "",
			"name": "MOGU"
		}, {
			"name_e": "XC2S",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "GFIVE G9",
			"name_c": "",
			"name": "基伍"
		}, {
			"name_e": "6530",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "M228",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "Heeyu_S009",
			"name_c": "",
			"name": "四季恒美"
		}, {
			"name_e": "QY N986",
			"name_c": "",
			"name": "中兴"
		}, {
			"name_e": "M16",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "A901",
			"name_c": "",
			"name": "传奇"
		}, {
			"name_e": "OKA5",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "I5-TD",
			"name_c": "",
			"name": "aomor"
		}, {
			"name_e": "SZF",
			"name_c": "",
			"name": "沃特沃德"
		}, {
			"name_e": "Bird XL100",
			"name_c": "枭龙",
			"name": "波导"
		}, {
			"name_e": "V008C",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "SPHS on Hsdroid",
			"name_c": "",
			"name": "WANJINTA"
		}, {
			"name_e": "U1205",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "C2",
			"name_c": "小黑",
			"name": "卓普"
		}, {
			"name_e": "A18",
			"name_c": "",
			"name": "派对"
		}, {
			"name_e": "S550",
			"name_c": "",
			"name": "Xianmi"
		}, {
			"name_e": "AUX T5010",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "C7",
			"name_c": "大黑",
			"name": "卓普"
		}, {
			"name_e": "JX8166",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "US518",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "M99",
			"name_c": "",
			"name": "IMI"
		}, {
			"name_e": "H6",
			"name_c": "",
			"name": "MOGU"
		}, {
			"name_e": "LS555I",
			"name_c": "",
			"name": "LANGSXINE"
		}, {
			"name_e": "PULID F19",
			"name_c": "刀锋",
			"name": "普莱达"
		}, {
			"name_e": "M128",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "MOGU T1",
			"name_c": "",
			"name": "七星河"
		}, {
			"name_e": "6560",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "QXH",
			"name_c": "",
			"name": "七星河"
		}, {
			"name_e": "6560",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "AUX I6T",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "S600",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "CIKAA",
			"name_c": "",
			"name": "CIKAA（喜卡）"
		}, {
			"name_e": "866",
			"name_c": "",
			"name": "龙讯"
		}, {
			"name_e": "I5-M1",
			"name_c": "",
			"name": "MIP"
		}, {
			"name_e": "V012D",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "U1203",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "I7100S",
			"name_c": "",
			"name": "晨信通"
		}, {
			"name_e": "X6_",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "HIKe 848",
			"name_c": "",
			"name": "海客"
		}, {
			"name_e": "F911G",
			"name_c": "",
			"name": "恒翔"
		}, {
			"name_e": "F7_",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "P68",
			"name_c": "",
			"name": "龙讯"
		}, {
			"name_e": "AUX V965T",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "M7",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "F7",
			"name_c": "",
			"name": "YK"
		}, {
			"name_e": "Q803",
			"name_c": "",
			"name": "小杨树"
		}, {
			"name_e": "ZOPO C2",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "9515",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "OKA6",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "Hy",
			"name_c": "",
			"name": "Phone"
		}, {
			"name_e": "GFIVE G9",
			"name_c": "",
			"name": "基伍"
		}, {
			"name_e": "U966",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "2013022",
			"name_c": "",
			"name": "小米"
		}, {
			"name_e": "V13_TD928",
			"name_c": "",
			"name": "LEEHOM"
		}, {
			"name_e": "CY8350",
			"name_c": "",
			"name": "创雅"
		}, {
			"name_e": "Coolpad 8079_T00",
			"name_c": "",
			"name": "酷派"
		}, {
			"name_e": "T350",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "C1",
			"name_c": "小白",
			"name": "卓普"
		}, {
			"name_e": "Coolpad 8079",
			"name_c": "",
			"name": "酷派"
		}, {
			"name_e": "IN320",
			"name_c": "",
			"name": "富士康"
		}, {
			"name_e": "GM",
			"name_c": "",
			"name": "CIKAA（喜卡）"
		}, {
			"name_e": "MH6000",
			"name_c": "",
			"name": "摩托罗拉"
		}, {
			"name_e": "lephone T708A",
			"name_c": "",
			"name": "百立丰"
		}, {
			"name_e": "UTime_GX",
			"name_c": "",
			"name": "UTime"
		}, {
			"name_e": "JY-F1",
			"name_c": "",
			"name": "佳域"
		}, {
			"name_e": "OUKI G6",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "M6A",
			"name_c": "",
			"name": "mikee"
		}, {
			"name_e": "XYS_Q802",
			"name_c": "",
			"name": "小杨树"
		}, {
			"name_e": "YK828_71",
			"name_c": "",
			"name": "沃特沃德"
		}, {
			"name_e": "CY8318",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "YK828_71",
			"name_c": "",
			"name": "沃特沃德"
		}, {
			"name_e": "TW108",
			"name_c": "",
			"name": "唐为"
		}, {
			"name_e": "US508",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "U558",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "TW168",
			"name_c": "",
			"name": "唐为"
		}, {
			"name_e": "C10",
			"name_c": "",
			"name": "恒翔"
		}, {
			"name_e": "lephone T708A",
			"name_c": "",
			"name": "百立丰"
		}, {
			"name_e": "F911G",
			"name_c": "",
			"name": "恒翔"
		}, {
			"name_e": "JX8166",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "CY8318",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "I7100S",
			"name_c": "",
			"name": "晨信通"
		}, {
			"name_e": "Coolpad 5310",
			"name_c": "",
			"name": "酷派"
		}, {
			"name_e": "FPC1011",
			"name_c": "",
			"name": "Amlogic"
		}, {
			"name_e": "OUKI G6",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "AUX V965T",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "M1",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "TruTalk-q903",
			"name_c": "",
			"name": "上海信云"
		}, {
			"name_e": "Bird XL200",
			"name_c": "",
			"name": "波导"
		}, {
			"name_e": "JX8155",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "K3",
			"name_c": "",
			"name": "纽曼"
		}, {
			"name_e": "N986",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "Philips S301",
			"name_c": "",
			"name": "桑菲"
		}, {
			"name_e": "Coolpad 5218S",
			"name_c": "",
			"name": "酷派"
		}, {
			"name_e": "D40",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "YK828_V30",
			"name_c": "",
			"name": "参考设计_沃特沃德"
		}, {
			"name_e": "EV9070-788",
			"name_c": "",
			"name": "东信"
		}, {
			"name_e": "XC2",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "even89_we_ali_jb2",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "ChanghongC606",
			"name_c": "",
			"name": "长虹-手机"
		}, {
			"name_e": "intki E89",
			"name_c": "",
			"name": "英特奇"
		}, {
			"name_e": "S660",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "DATANG S55",
			"name_c": "",
			"name": "大唐"
		}, {
			"name_e": "M_3",
			"name_c": "",
			"name": "万米"
		}, {
			"name_e": "AUX T5010",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "C10",
			"name_c": "",
			"name": "恒翔"
		}, {
			"name_e": "X6099",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "S800",
			"name_c": "",
			"name": "Xianmi"
		}, {
			"name_e": "V9180",
			"name_c": "",
			"name": "中兴"
		}, {
			"name_e": "KB8286",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "YK828_V30",
			"name_c": "",
			"name": "参考设计_沃特沃德"
		}, {
			"name_e": "C5",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "M17",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "M18",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "IMI",
			"name_c": "",
			"name": "顺隆"
		}, {
			"name_e": "JX8155",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "X6_",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "F1",
			"name_c": "",
			"name": "夏米"
		}, {
			"name_e": "Lenovo",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "OUKI A56",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "UNISTAR U5",
			"name_c": "",
			"name": "友信达"
		}, {
			"name_e": "Cayon A2",
			"name_c": "",
			"name": "易合纵"
		}, {
			"name_e": "J2",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "XYS_Q800",
			"name_c": "",
			"name": "XYS"
		}, {
			"name_e": "LINGWIN",
			"name_c": "",
			"name": "聆韵"
		}, {
			"name_e": "S301",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "FPC1011",
			"name_c": "",
			"name": "Amlogic"
		}, {
			"name_e": "Heeyu_S009",
			"name_c": "",
			"name": "四季恒美"
		}, {
			"name_e": "4G",
			"name_c": "",
			"name": "三魅"
		}, {
			"name_e": "S600",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "U1203",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "intki E76",
			"name_c": "",
			"name": "英特奇"
		}, {
			"name_e": "YUSUN T55",
			"name_c": "",
			"name": "语信"
		}, {
			"name_e": "6530",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "HS-U980",
			"name_c": "",
			"name": "海信"
		}, {
			"name_e": "T06-A",
			"name_c": "",
			"name": "中可"
		}, {
			"name_e": "V015",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "US528",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "Bird i900",
			"name_c": "",
			"name": "波导"
		}, {
			"name_e": "Bird i900",
			"name_c": "",
			"name": "波导"
		}, {
			"name_e": "M3",
			"name_c": "",
			"name": "LINGMI"
		}, {
			"name_e": "HW-E6",
			"name_c": "",
			"name": "新虹伟"
		}, {
			"name_e": "V88",
			"name_c": "",
			"name": "锦润"
		}, {
			"name_e": "ZOPO 9520",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "M13",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "A6500",
			"name_c": "",
			"name": "鑫华美"
		}, {
			"name_e": "A6500",
			"name_c": "",
			"name": "鑫华美"
		}, {
			"name_e": "I9220",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "Q9",
			"name_c": "",
			"name": "万维科"
		}, {
			"name_e": "SPHS on Hsdroid",
			"name_c": "",
			"name": "WANJINTA"
		}, {
			"name_e": "A901",
			"name_c": "",
			"name": "传奇"
		}, {
			"name_e": "A902",
			"name_c": "",
			"name": "SAGA"
		}, {
			"name_e": "OKU3",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "M17",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "U8",
			"name_c": "",
			"name": "UBTEL"
		}, {
			"name_e": "V015A",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "YIMI_828",
			"name_c": "",
			"name": "金盛"
		}, {
			"name_e": "epade A3",
			"name_c": "",
			"name": "尼奥"
		}, {
			"name_e": "lenovo",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "866",
			"name_c": "",
			"name": "龙讯"
		}, {
			"name_e": "HIKe Z1",
			"name_c": "",
			"name": "海客"
		}, {
			"name_e": "UALA03",
			"name_c": "",
			"name": "果冻"
		}, {
			"name_e": "A905",
			"name_c": "",
			"name": "诺亚信"
		}, {
			"name_e": "A905",
			"name_c": "",
			"name": "诺亚信"
		}, {
			"name_e": "LA-M1Y",
			"name_c": "M1Y",
			"name": "小辣椒"
		}, {
			"name_e": "TruTalk-q903",
			"name_c": "",
			"name": "上海信云"
		}, {
			"name_e": "V003",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "TW108",
			"name_c": "",
			"name": "唐为"
		}, {
			"name_e": "P7",
			"name_c": "",
			"name": "佳业"
		}, {
			"name_e": "未知机型",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "C7T",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "X11",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "oppo",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "D30",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "XG x800",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "T9986",
			"name_c": "",
			"name": "TELSDA"
		}, {
			"name_e": "UNISTAR U1",
			"name_c": "",
			"name": "友信达"
		}, {
			"name_e": "UNISTAR U1",
			"name_c": "",
			"name": "友信达"
		}, {
			"name_e": "UTime U9",
			"name_c": "",
			"name": "UTime"
		}, {
			"name_e": "GO N1",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "voto v5",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "Neken P5005B",
			"name_c": "",
			"name": "尼凯恩"
		}, {
			"name_e": "Q3 mini",
			"name_c": "",
			"name": "cayon"
		}, {
			"name_e": "X16",
			"name_c": "",
			"name": "Xmi"
		}, {
			"name_e": "T6100",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "AUX V950AW",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "BIMI 4502",
			"name_c": "",
			"name": "波导"
		}, {
			"name_e": "SAGA",
			"name_c": "",
			"name": "SAGA"
		}, {
			"name_e": "SAGA",
			"name_c": "",
			"name": "SAGA"
		}, {
			"name_e": "BROR W65",
			"name_c": "",
			"name": "博瑞世纪"
		}, {
			"name_e": "V008C",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "Q803",
			"name_c": "",
			"name": "小杨树"
		}, {
			"name_e": "T350",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "T963",
			"name_c": "",
			"name": "华森"
		}, {
			"name_e": "W6A",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "AUX I6T",
			"name_c": "",
			"name": "奥克斯"
		}, {
			"name_e": "U558",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "guomi-F1",
			"name_c": "",
			"name": "GUOMI"
		}, {
			"name_e": "A18",
			"name_c": "",
			"name": "派对"
		}, {
			"name_e": "CY8310",
			"name_c": "",
			"name": "宝捷讯"
		}, {
			"name_e": "XYS_Q800",
			"name_c": "",
			"name": "XYS"
		}, {
			"name_e": "Ding Zhi Ban",
			"name_c": "",
			"name": "小杨树"
		}, {
			"name_e": "HL089",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "U558S",
			"name_c": "",
			"name": "优思"
		}, {
			"name_e": "ZP600",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "ZP600",
			"name_c": "",
			"name": "卓普"
		}, {
			"name_e": "A101",
			"name_c": "",
			"name": "MT"
		}, {
			"name_e": "LINGWIN",
			"name_c": "",
			"name": "聆韵"
		}, {
			"name_e": "KS801",
			"name_c": "",
			"name": "kevoo"
		}, {
			"name_e": "RX",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "Q22",
			"name_c": "",
			"name": "红星"
		}, {
			"name_e": "HUAWEI",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "QXH",
			"name_c": "",
			"name": "七星河"
		}, {
			"name_e": "MT",
			"name_c": "",
			"name": "MT"
		}, {
			"name_e": "S301",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "MT",
			"name_c": "",
			"name": "MT"
		}, {
			"name_e": "A102",
			"name_c": "",
			"name": "MT"
		}, {
			"name_e": "A800i",
			"name_c": "",
			"name": "基伍"
		}, {
			"name_e": "EF98",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "M010",
			"name_c": "",
			"name": "DUXIU"
		}, {
			"name_e": "Intki E75",
			"name_c": "",
			"name": "英特奇"
		}, {
			"name_e": "M128",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "V8",
			"name_c": "",
			"name": "YK"
		}, {
			"name_e": "V8",
			"name_c": "",
			"name": "YK"
		}, {
			"name_e": "HuaQiang_H60",
			"name_c": "",
			"name": "华强"
		}, {
			"name_e": "4G",
			"name_c": "",
			"name": "三魅"
		}, {
			"name_e": "I5-TD",
			"name_c": "",
			"name": "aomor"
		}, {
			"name_e": "RSD",
			"name_c": "",
			"name": "RSD"
		}, {
			"name_e": "OKA6",
			"name_c": "",
			"name": "欧奇"
		}, {
			"name_e": "ZTE",
			"name_c": "",
			"name": "广鑫"
		}, {
			"name_e": "AMOI N880",
			"name_c": "",
			"name": "夏新"
		}, {
			"name_e": "intki E76",
			"name_c": "",
			"name": "英特奇"
		}, {
			"name_e": "M10",
			"name_c": "",
			"name": "华凌"
		}, {
			"name_e": "MOFUT_A1",
			"name_c": "",
			"name": "参考设计_豪成"
		}, {
			"name_e": "U1",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "H60",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "H60",
			"name_c": "",
			"name": ""
		}, {
			"name_e": "U1205",
			"name_c": "",
			"name": "优思"
		}]
	};
	return data
});